/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as BoqRouteImport } from './routes/boq'
import { Route as DailySummaryRouteImport } from './routes/daily-summary'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManpowerRouteImport } from './routes/manpower'
import { Route as MaterialRouteImport } from './routes/material'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as PoLogRouteImport } from './routes/po-log'
import { Route as TowerARouteImport } from './routes/tower-a'
import { Route as TowerBRouteImport } from './routes/tower-b'
import { Route as ApiDailySummaryRouteImport } from './routes/api/daily-summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BoqRoute = BoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => rootRouteImport,
} as any)
const DailySummaryRoute = DailySummaryRouteImport.update({
  id: '/daily-summary',
  path: '/daily-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManpowerRoute = ManpowerRouteImport.update({
  id: '/manpower',
  path: '/manpower',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialRoute = MaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoLogRoute = PoLogRouteImport.update({
  id: '/po-log',
  path: '/po-log',
  getParentRoute: () => rootRouteImport,
} as any)
const TowerARoute = TowerARouteImport.update({
  id: '/tower-a',
  path: '/tower-a',
  getParentRoute: () => rootRouteImport,
} as any)
const TowerBRoute = TowerBRouteImport.update({
  id: '/tower-b',
  path: '/tower-b',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailySummaryRoute = ApiDailySummaryRouteImport.update({
  id: '/api/daily-summary',
  path: '/api/daily-summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/boq': typeof BoqRoute
  '/daily-summary': typeof DailySummaryRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/manpower': typeof ManpowerRoute
  '/material': typeof MaterialRoute
  '/matrix': typeof MatrixRoute
  '/photos': typeof PhotosRoute
  '/po-log': typeof PoLogRoute
  '/tower-a': typeof TowerARoute
  '/tower-b': typeof TowerBRoute
  '/api/daily-summary': typeof ApiDailySummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/boq': typeof BoqRoute
  '/daily-summary': typeof DailySummaryRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/manpower': typeof ManpowerRoute
  '/material': typeof MaterialRoute
  '/matrix': typeof MatrixRoute
  '/photos': typeof PhotosRoute
  '/po-log': typeof PoLogRoute
  '/tower-a': typeof TowerARoute
  '/tower-b': typeof TowerBRoute
  '/api/daily-summary': typeof ApiDailySummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/boq': typeof BoqRoute
  '/daily-summary': typeof DailySummaryRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/manpower': typeof ManpowerRoute
  '/material': typeof MaterialRoute
  '/matrix': typeof MatrixRoute
  '/photos': typeof PhotosRoute
  '/po-log': typeof PoLogRoute
  '/tower-a': typeof TowerARoute
  '/tower-b': typeof TowerBRoute
  '/api/daily-summary': typeof ApiDailySummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/boq'
    | '/daily-summary'
    | '/home'
    | '/library'
    | '/login'
    | '/manpower'
    | '/material'
    | '/matrix'
    | '/photos'
    | '/po-log'
    | '/tower-a'
    | '/tower-b'
    | '/api/daily-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/boq'
    | '/daily-summary'
    | '/home'
    | '/library'
    | '/login'
    | '/manpower'
    | '/material'
    | '/matrix'
    | '/photos'
    | '/po-log'
    | '/tower-a'
    | '/tower-b'
    | '/api/daily-summary'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/boq'
    | '/daily-summary'
    | '/home'
    | '/library'
    | '/login'
    | '/manpower'
    | '/material'
    | '/matrix'
    | '/photos'
    | '/po-log'
    | '/tower-a'
    | '/tower-b'
    | '/api/daily-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BoqRoute: typeof BoqRoute
  DailySummaryRoute: typeof DailySummaryRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ManpowerRoute: typeof ManpowerRoute
  MaterialRoute: typeof MaterialRoute
  MatrixRoute: typeof MatrixRoute
  PhotosRoute: typeof PhotosRoute
  PoLogRoute: typeof PoLogRoute
  TowerARoute: typeof TowerARoute
  TowerBRoute: typeof TowerBRoute
  ApiDailySummaryRoute: typeof ApiDailySummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boq': {
      id: '/boq'
      path: '/boq'
      fullPath: '/boq'
      preLoaderRoute: typeof BoqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-summary': {
      id: '/daily-summary'
      path: '/daily-summary'
      fullPath: '/daily-summary'
      preLoaderRoute: typeof DailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manpower': {
      id: '/manpower'
      path: '/manpower'
      fullPath: '/manpower'
      preLoaderRoute: typeof ManpowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material': {
      id: '/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof MaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po-log': {
      id: '/po-log'
      path: '/po-log'
      fullPath: '/po-log'
      preLoaderRoute: typeof PoLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tower-a': {
      id: '/tower-a'
      path: '/tower-a'
      fullPath: '/tower-a'
      preLoaderRoute: typeof TowerARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tower-b': {
      id: '/tower-b'
      path: '/tower-b'
      fullPath: '/tower-b'
      preLoaderRoute: typeof TowerBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-summary': {
      id: '/api/daily-summary'
      path: '/api/daily-summary'
      fullPath: '/api/daily-summary'
      preLoaderRoute: typeof ApiDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BoqRoute: BoqRoute,
  DailySummaryRoute: DailySummaryRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ManpowerRoute: ManpowerRoute,
  MaterialRoute: MaterialRoute,
  MatrixRoute: MatrixRoute,
  PhotosRoute: PhotosRoute,
  PoLogRoute: PoLogRoute,
  TowerARoute: TowerARoute,
  TowerBRoute: TowerBRoute,
  ApiDailySummaryRoute: ApiDailySummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
